# Generated by Django 5.1.1 on 2024-10-08 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('porcentaje', models.FloatField(default=0)),
                ('fechaInicio', models.DateField(default='2024-01-01')),
                ('fechaFinal', models.DateField(default='2024-01-01')),
                ('fechaCreacion', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(default=1)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('logo', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=255)),
                ('nombre', models.CharField(max_length=50)),
                ('contrasenia', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=50)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.institucion')),
            ],
        ),
        migrations.CreateModel(
            name='Cronograma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField(default=2024)),
                ('nombre', models.CharField(max_length=100)),
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='pagos.curso')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='estudiantes',
            field=models.ManyToManyField(to='pagos.estudiante'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.institucion'),
        ),
        migrations.AddField(
            model_name='curso',
            name='institucion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.institucion'),
        ),
        migrations.CreateModel(
            name='Responsablef',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pagos.usuario')),
                ('estudiantes', models.ManyToManyField(to='pagos.estudiante')),
            ],
            bases=('pagos.usuario',),
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField(default='2024-01-01')),
                ('valor', models.FloatField(default=0)),
                ('interes', models.FloatField(default=0)),
                ('pagado', models.BooleanField(default=False)),
                ('tipo', models.CharField(max_length=50)),
                ('periodicidad', models.IntegerField(default=0)),
                ('cronograma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.cronograma')),
                ('descuento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pagos.descuento')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.estudiante')),
                ('responsableF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pagos.responsablef')),
            ],
        ),
    ]
