# Generated by Django 3.2.6 on 2024-11-15 22:10

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha',
            field=django_cryptography.fields.encrypt(models.CharField(default='2024-01-01', max_length=50)),
        ),
        migrations.AlterField(
            model_name='pago',
            name='interes',
            field=django_cryptography.fields.encrypt(models.CharField(default=0, max_length=50)),
        ),
        migrations.AlterField(
            model_name='pago',
            name='pagado',
            field=django_cryptography.fields.encrypt(models.CharField(default=False, max_length=50)),
        ),
        migrations.AlterField(
            model_name='pago',
            name='periodicidad',
            field=django_cryptography.fields.encrypt(models.CharField(default=0, max_length=50)),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tipo',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=50)),
        ),
        migrations.AlterField(
            model_name='pago',
            name='valor',
            field=django_cryptography.fields.encrypt(models.CharField(default=0, max_length=50)),
        ),
    ]
