# Generated by Django 3.2.6 on 2024-11-15 22:26

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_auto_20241115_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha',
            field=django_cryptography.fields.encrypt(models.DateTimeField(default='2024-01-01')),
        ),
        migrations.AlterField(
            model_name='pago',
            name='interes',
            field=django_cryptography.fields.encrypt(models.FloatField(default=0)),
        ),
        migrations.AlterField(
            model_name='pago',
            name='nombre',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=50)),
        ),
        migrations.AlterField(
            model_name='pago',
            name='pagado',
            field=django_cryptography.fields.encrypt(models.BooleanField(default=False)),
        ),
        migrations.AlterField(
            model_name='pago',
            name='periodicidad',
            field=django_cryptography.fields.encrypt(models.IntegerField(default=0)),
        ),
        migrations.AlterField(
            model_name='pago',
            name='valor',
            field=django_cryptography.fields.encrypt(models.FloatField(default=0)),
        ),
    ]
