# Generated by Django 3.2.6 on 2024-11-15 22:36

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_auto_20241115_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='fecha',
            field=django_cryptography.fields.encrypt(models.DateTimeField(default=None, null=True)),
        ),
        migrations.AlterField(
            model_name='pago',
            name='interes',
            field=django_cryptography.fields.encrypt(models.FloatField(default=None, null=True)),
        ),
        migrations.AlterField(
            model_name='pago',
            name='nombre',
            field=django_cryptography.fields.encrypt(models.CharField(default=None, max_length=50, null=True)),
        ),
        migrations.AlterField(
            model_name='pago',
            name='pagado',
            field=django_cryptography.fields.encrypt(models.BooleanField(default=None, null=True)),
        ),
        migrations.AlterField(
            model_name='pago',
            name='periodicidad',
            field=django_cryptography.fields.encrypt(models.IntegerField(default=None, null=True)),
        ),
        migrations.AlterField(
            model_name='pago',
            name='tipo',
            field=django_cryptography.fields.encrypt(models.CharField(default=None, max_length=50, null=True)),
        ),
        migrations.AlterField(
            model_name='pago',
            name='valor',
            field=django_cryptography.fields.encrypt(models.FloatField(default=None, null=True)),
        ),
    ]
